import json

sky_response = {
    "_parameters": {"latitude": "40.7128", "longitude": "-74.0060", "time": None},
    "_queries": {},
    "timeout": None,
    "response_headers": {
        "Date": "Sun, 04 Apr 2021 20:50:45 GMT",
        "Content-Type": "application/json; charset=utf-8",
        "Transfer-Encoding": "chunked",
        "Connection": "keep-alive",
        "Strict-Transport-Security": "max-age=31536000",
        "X-Authentication-Time": "174ms",
        "X-Forecast-API-Calls": "631",
        "Cache-Control": "max-age=60",
        "Expires": "Sun, 04 Apr 2021 20:51:45 +0000",
        "X-Response-Time": "127.616ms",
        "Vary": "Accept-Encoding",
        "Content-Encoding": "gzip",
    },
    "_data": {
        "latitude": 40.7128,
        "longitude": -74.006,
        "timezone": "America/New_York",
        "currently": {
            "time": 1617569445,
            "summary": "Clear",
            "icon": "clear-day",
            "nearestStormDistance": 29,
            "nearestStormBearing": 190,
            "precipIntensity": 0,
            "precipProbability": 0,
            "temperature": 59.68,
            "apparentTemperature": 59.68,
            "dewPoint": 32.48,
            "humidity": 0.36,
            "pressure": 1014.9,
            "windSpeed": 2.81,
            "windGust": 14.29,
            "windBearing": 269,
            "cloudCover": 0.06,
            "uvIndex": 1,
            "visibility": 10,
            "ozone": 387.7,
        },
        "minutely": {
            "summary": "Clear for the hour.",
            "icon": "clear-day",
            "data": [
                {"time": 1617569400, "precipIntensity": 0, "precipProbability": 0},
                {"time": 1617569460, "precipIntensity": 0, "precipProbability": 0},
                {"time": 1617569520, "precipIntensity": 0, "precipProbability": 0},
                {"time": 1617569580, "precipIntensity": 0, "precipProbability": 0},
                {"time": 1617569640, "precipIntensity": 0, "precipProbability": 0},
                {"time": 1617569700, "precipIntensity": 0, "precipProbability": 0},
                {"time": 1617569760, "precipIntensity": 0, "precipProbability": 0},
                {
                    "time": 1617569820,
                    "precipIntensity": 0.0028,
                    "precipIntensityError": 0.0006,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                },
                {
                    "time": 1617569880,
                    "precipIntensity": 0.0029,
                    "precipIntensityError": 0.0007,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                },
                {
                    "time": 1617569940,
                    "precipIntensity": 0.0027,
                    "precipIntensityError": 0.0007,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                },
                {
                    "time": 1617570000,
                    "precipIntensity": 0.0028,
                    "precipIntensityError": 0.0006,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                },
                {"time": 1617570060, "precipIntensity": 0, "precipProbability": 0},
                {
                    "time": 1617570120,
                    "precipIntensity": 0.0028,
                    "precipIntensityError": 0.0007,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                },
                {
                    "time": 1617570180,
                    "precipIntensity": 0.0026,
                    "precipIntensityError": 0.0007,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                },
                {"time": 1617570240, "precipIntensity": 0, "precipProbability": 0},
                {
                    "time": 1617570300,
                    "precipIntensity": 0.0029,
                    "precipIntensityError": 0.0008,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                },
                {
                    "time": 1617570360,
                    "precipIntensity": 0.0028,
                    "precipIntensityError": 0.0007,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617570420,
                    "precipIntensity": 0.0028,
                    "precipIntensityError": 0.0008,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617570480,
                    "precipIntensity": 0.0028,
                    "precipIntensityError": 0.0008,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617570540,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.0008,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617570600,
                    "precipIntensity": 0.0029,
                    "precipIntensityError": 0.0008,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617570660,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.0009,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617570720,
                    "precipIntensity": 0.0029,
                    "precipIntensityError": 0.0009,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617570780,
                    "precipIntensity": 0.0028,
                    "precipIntensityError": 0.0008,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617570840,
                    "precipIntensity": 0.0029,
                    "precipIntensityError": 0.0008,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617570900,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.0008,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617570960,
                    "precipIntensity": 0.0029,
                    "precipIntensityError": 0.0008,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617571020,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.0009,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617571080,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.0008,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617571140,
                    "precipIntensity": 0.0029,
                    "precipIntensityError": 0.0009,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617571200,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.001,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617571260,
                    "precipIntensity": 0.0029,
                    "precipIntensityError": 0.0008,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617571320,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.0009,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617571380,
                    "precipIntensity": 0.0029,
                    "precipIntensityError": 0.001,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617571440,
                    "precipIntensity": 0.0029,
                    "precipIntensityError": 0.0009,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617571500,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.001,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617571560,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.0009,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617571620,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.001,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617571680,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.001,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617571740,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.0011,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617571800,
                    "precipIntensity": 0.0032,
                    "precipIntensityError": 0.0015,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617571860,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.0009,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617571920,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.001,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617571980,
                    "precipIntensity": 0.0029,
                    "precipIntensityError": 0.0009,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617572040,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.0011,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617572100,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.001,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617572160,
                    "precipIntensity": 0.0032,
                    "precipIntensityError": 0.0013,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617572220,
                    "precipIntensity": 0.0031,
                    "precipIntensityError": 0.0011,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                },
                {
                    "time": 1617572280,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.0011,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617572340,
                    "precipIntensity": 0.0031,
                    "precipIntensityError": 0.0015,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617572400,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.0011,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617572460,
                    "precipIntensity": 0.003,
                    "precipIntensityError": 0.001,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617572520,
                    "precipIntensity": 0.0032,
                    "precipIntensityError": 0.0014,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617572580,
                    "precipIntensity": 0.0031,
                    "precipIntensityError": 0.001,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617572640,
                    "precipIntensity": 0.0032,
                    "precipIntensityError": 0.0014,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {"time": 1617572700, "precipIntensity": 0, "precipProbability": 0},
                {
                    "time": 1617572760,
                    "precipIntensity": 0.0032,
                    "precipIntensityError": 0.0012,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617572820,
                    "precipIntensity": 0.0031,
                    "precipIntensityError": 0.0013,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617572880,
                    "precipIntensity": 0.0031,
                    "precipIntensityError": 0.0014,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617572940,
                    "precipIntensity": 0.0031,
                    "precipIntensityError": 0.0014,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
                {
                    "time": 1617573000,
                    "precipIntensity": 0.0033,
                    "precipIntensityError": 0.0015,
                    "precipProbability": 0.03,
                    "precipType": "rain",
                },
            ],
        },
        "hourly": {
            "summary": "Clear throughout the day.",
            "icon": "clear-day",
            "data": [
                {
                    "time": 1617566400,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 58.93,
                    "apparentTemperature": 58.93,
                    "dewPoint": 31.48,
                    "humidity": 0.35,
                    "pressure": 1015.1,
                    "windSpeed": 2.07,
                    "windGust": 12.61,
                    "windBearing": 310,
                    "cloudCover": 0.03,
                    "uvIndex": 3,
                    "visibility": 10,
                    "ozone": 390.2,
                },
                {
                    "time": 1617570000,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0.0016,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                    "temperature": 59.72,
                    "apparentTemperature": 59.72,
                    "dewPoint": 32.62,
                    "humidity": 0.36,
                    "pressure": 1014.9,
                    "windSpeed": 2.98,
                    "windGust": 14.47,
                    "windBearing": 266,
                    "cloudCover": 0.06,
                    "uvIndex": 1,
                    "visibility": 10,
                    "ozone": 387.4,
                },
                {
                    "time": 1617573600,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0.0011,
                    "precipProbability": 0.04,
                    "precipType": "rain",
                    "temperature": 58.87,
                    "apparentTemperature": 58.87,
                    "dewPoint": 33.5,
                    "humidity": 0.38,
                    "pressure": 1014.8,
                    "windSpeed": 3.54,
                    "windGust": 14.59,
                    "windBearing": 250,
                    "cloudCover": 0.09,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 386.9,
                },
                {
                    "time": 1617577200,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 56.73,
                    "apparentTemperature": 56.73,
                    "dewPoint": 34.51,
                    "humidity": 0.43,
                    "pressure": 1015.3,
                    "windSpeed": 6.44,
                    "windGust": 13.52,
                    "windBearing": 287,
                    "cloudCover": 0.14,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 388.3,
                },
                {
                    "time": 1617580800,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 54.66,
                    "apparentTemperature": 54.66,
                    "dewPoint": 38.22,
                    "humidity": 0.54,
                    "pressure": 1016,
                    "windSpeed": 7.35,
                    "windGust": 14.06,
                    "windBearing": 306,
                    "cloudCover": 0.23,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 390.6,
                },
                {
                    "time": 1617584400,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 53.68,
                    "apparentTemperature": 53.68,
                    "dewPoint": 38.5,
                    "humidity": 0.56,
                    "pressure": 1016.6,
                    "windSpeed": 7.67,
                    "windGust": 14.51,
                    "windBearing": 316,
                    "cloudCover": 0.11,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 390.7,
                },
                {
                    "time": 1617588000,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 52.46,
                    "apparentTemperature": 52.46,
                    "dewPoint": 39.24,
                    "humidity": 0.61,
                    "pressure": 1017.1,
                    "windSpeed": 9.36,
                    "windGust": 18.85,
                    "windBearing": 338,
                    "cloudCover": 0.06,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 390.6,
                },
                {
                    "time": 1617591600,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 51.74,
                    "apparentTemperature": 51.74,
                    "dewPoint": 39.04,
                    "humidity": 0.62,
                    "pressure": 1017.7,
                    "windSpeed": 9.75,
                    "windGust": 19.73,
                    "windBearing": 340,
                    "cloudCover": 0.02,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 392.2,
                },
                {
                    "time": 1617595200,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 51.05,
                    "apparentTemperature": 51.05,
                    "dewPoint": 38.4,
                    "humidity": 0.62,
                    "pressure": 1017.6,
                    "windSpeed": 9.28,
                    "windGust": 19.81,
                    "windBearing": 339,
                    "cloudCover": 0.01,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 395.2,
                },
                {
                    "time": 1617598800,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 50.32,
                    "apparentTemperature": 50.32,
                    "dewPoint": 37.65,
                    "humidity": 0.62,
                    "pressure": 1017.4,
                    "windSpeed": 8.85,
                    "windGust": 19.31,
                    "windBearing": 338,
                    "cloudCover": 0.01,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 396.8,
                },
                {
                    "time": 1617602400,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 49.77,
                    "apparentTemperature": 46.32,
                    "dewPoint": 36.89,
                    "humidity": 0.61,
                    "pressure": 1017,
                    "windSpeed": 8.41,
                    "windGust": 18.16,
                    "windBearing": 327,
                    "cloudCover": 0.01,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 395.7,
                },
                {
                    "time": 1617606000,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 48.61,
                    "apparentTemperature": 44.68,
                    "dewPoint": 36.13,
                    "humidity": 0.62,
                    "pressure": 1016.9,
                    "windSpeed": 8.96,
                    "windGust": 19.6,
                    "windBearing": 319,
                    "cloudCover": 0.01,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 393.7,
                },
                {
                    "time": 1617609600,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 47.66,
                    "apparentTemperature": 43.2,
                    "dewPoint": 35.3,
                    "humidity": 0.62,
                    "pressure": 1016.9,
                    "windSpeed": 9.82,
                    "windGust": 20.56,
                    "windBearing": 318,
                    "cloudCover": 0,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 394.2,
                },
                {
                    "time": 1617613200,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 46.73,
                    "apparentTemperature": 41.85,
                    "dewPoint": 34.73,
                    "humidity": 0.63,
                    "pressure": 1017,
                    "windSpeed": 10.36,
                    "windGust": 21.29,
                    "windBearing": 314,
                    "cloudCover": 0.01,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 396.1,
                },
                {
                    "time": 1617616800,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 46.2,
                    "apparentTemperature": 41.22,
                    "dewPoint": 34.01,
                    "humidity": 0.62,
                    "pressure": 1017.2,
                    "windSpeed": 10.29,
                    "windGust": 23.16,
                    "windBearing": 316,
                    "cloudCover": 0.01,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 397.5,
                },
                {
                    "time": 1617620400,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 45.69,
                    "apparentTemperature": 40.54,
                    "dewPoint": 34.05,
                    "humidity": 0.64,
                    "pressure": 1017.5,
                    "windSpeed": 10.43,
                    "windGust": 23.33,
                    "windBearing": 318,
                    "cloudCover": 0.01,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 400,
                },
                {
                    "time": 1617624000,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 46.07,
                    "apparentTemperature": 40.83,
                    "dewPoint": 34.12,
                    "humidity": 0.63,
                    "pressure": 1017.7,
                    "windSpeed": 10.94,
                    "windGust": 23.19,
                    "windBearing": 319,
                    "cloudCover": 0.01,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 399.5,
                },
                {
                    "time": 1617627600,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 47.55,
                    "apparentTemperature": 42.43,
                    "dewPoint": 34.13,
                    "humidity": 0.59,
                    "pressure": 1017.5,
                    "windSpeed": 11.69,
                    "windGust": 21.65,
                    "windBearing": 323,
                    "cloudCover": 0.01,
                    "uvIndex": 1,
                    "visibility": 10,
                    "ozone": 398.6,
                },
                {
                    "time": 1617631200,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 49.59,
                    "apparentTemperature": 44.83,
                    "dewPoint": 33.72,
                    "humidity": 0.54,
                    "pressure": 1017.4,
                    "windSpeed": 12.27,
                    "windGust": 21.03,
                    "windBearing": 326,
                    "cloudCover": 0.01,
                    "uvIndex": 3,
                    "visibility": 10,
                    "ozone": 397.9,
                },
                {
                    "time": 1617634800,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 51.38,
                    "apparentTemperature": 51.38,
                    "dewPoint": 32.88,
                    "humidity": 0.49,
                    "pressure": 1016.8,
                    "windSpeed": 12.85,
                    "windGust": 21.38,
                    "windBearing": 327,
                    "cloudCover": 0.01,
                    "uvIndex": 4,
                    "visibility": 10,
                    "ozone": 398.9,
                },
                {
                    "time": 1617638400,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 53.13,
                    "apparentTemperature": 53.13,
                    "dewPoint": 31.88,
                    "humidity": 0.44,
                    "pressure": 1016.1,
                    "windSpeed": 13.67,
                    "windGust": 21.83,
                    "windBearing": 323,
                    "cloudCover": 0.01,
                    "uvIndex": 5,
                    "visibility": 10,
                    "ozone": 399.8,
                },
                {
                    "time": 1617642000,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 54.73,
                    "apparentTemperature": 54.73,
                    "dewPoint": 31.36,
                    "humidity": 0.41,
                    "pressure": 1015.2,
                    "windSpeed": 14.11,
                    "windGust": 21.84,
                    "windBearing": 320,
                    "cloudCover": 0.03,
                    "uvIndex": 5,
                    "visibility": 10,
                    "ozone": 399.3,
                },
                {
                    "time": 1617645600,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 56.75,
                    "apparentTemperature": 56.75,
                    "dewPoint": 30.81,
                    "humidity": 0.37,
                    "pressure": 1014.6,
                    "windSpeed": 14.21,
                    "windGust": 22.62,
                    "windBearing": 316,
                    "cloudCover": 0.01,
                    "uvIndex": 5,
                    "visibility": 10,
                    "ozone": 397.8,
                },
                {
                    "time": 1617649200,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 58.52,
                    "apparentTemperature": 58.52,
                    "dewPoint": 29.55,
                    "humidity": 0.33,
                    "pressure": 1013.9,
                    "windSpeed": 14.67,
                    "windGust": 22.88,
                    "windBearing": 316,
                    "cloudCover": 0.01,
                    "uvIndex": 4,
                    "visibility": 10,
                    "ozone": 396.5,
                },
                {
                    "time": 1617652800,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 59.77,
                    "apparentTemperature": 59.77,
                    "dewPoint": 27.76,
                    "humidity": 0.29,
                    "pressure": 1013.3,
                    "windSpeed": 15.28,
                    "windGust": 23.65,
                    "windBearing": 318,
                    "cloudCover": 0.03,
                    "uvIndex": 3,
                    "visibility": 10,
                    "ozone": 394.8,
                },
                {
                    "time": 1617656400,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 59.78,
                    "apparentTemperature": 59.78,
                    "dewPoint": 26.96,
                    "humidity": 0.28,
                    "pressure": 1013.1,
                    "windSpeed": 15.56,
                    "windGust": 24.4,
                    "windBearing": 319,
                    "cloudCover": 0.11,
                    "uvIndex": 1,
                    "visibility": 10,
                    "ozone": 392.8,
                },
                {
                    "time": 1617660000,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 58.98,
                    "apparentTemperature": 58.98,
                    "dewPoint": 27.94,
                    "humidity": 0.3,
                    "pressure": 1013.3,
                    "windSpeed": 14.52,
                    "windGust": 23.93,
                    "windBearing": 319,
                    "cloudCover": 0.18,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 391.9,
                },
                {
                    "time": 1617663600,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 57.25,
                    "apparentTemperature": 57.25,
                    "dewPoint": 30.09,
                    "humidity": 0.35,
                    "pressure": 1014,
                    "windSpeed": 12.89,
                    "windGust": 23.97,
                    "windBearing": 321,
                    "cloudCover": 0.26,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 390.5,
                },
                {
                    "time": 1617667200,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 55.64,
                    "apparentTemperature": 55.64,
                    "dewPoint": 31.55,
                    "humidity": 0.4,
                    "pressure": 1014.4,
                    "windSpeed": 12.46,
                    "windGust": 23.98,
                    "windBearing": 322,
                    "cloudCover": 0.28,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 391.9,
                },
                {
                    "time": 1617670800,
                    "summary": "Partly Cloudy",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 54.44,
                    "apparentTemperature": 54.44,
                    "dewPoint": 31.68,
                    "humidity": 0.42,
                    "pressure": 1014.6,
                    "windSpeed": 12.02,
                    "windGust": 24.01,
                    "windBearing": 325,
                    "cloudCover": 0.44,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 390.2,
                },
                {
                    "time": 1617674400,
                    "summary": "Partly Cloudy",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 53.68,
                    "apparentTemperature": 53.68,
                    "dewPoint": 31.45,
                    "humidity": 0.43,
                    "pressure": 1014.9,
                    "windSpeed": 11.61,
                    "windGust": 23.8,
                    "windBearing": 329,
                    "cloudCover": 0.5,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 387.6,
                },
                {
                    "time": 1617678000,
                    "summary": "Mostly Cloudy",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 53.05,
                    "apparentTemperature": 53.05,
                    "dewPoint": 31.56,
                    "humidity": 0.44,
                    "pressure": 1015.1,
                    "windSpeed": 10.91,
                    "windGust": 22.33,
                    "windBearing": 331,
                    "cloudCover": 0.8,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 387,
                },
                {
                    "time": 1617681600,
                    "summary": "Mostly Cloudy",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 52.48,
                    "apparentTemperature": 52.48,
                    "dewPoint": 32.07,
                    "humidity": 0.46,
                    "pressure": 1015.1,
                    "windSpeed": 9.98,
                    "windGust": 20.73,
                    "windBearing": 331,
                    "cloudCover": 0.73,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 387.6,
                },
                {
                    "time": 1617685200,
                    "summary": "Partly Cloudy",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 51.72,
                    "apparentTemperature": 51.72,
                    "dewPoint": 32.78,
                    "humidity": 0.48,
                    "pressure": 1014.9,
                    "windSpeed": 8.86,
                    "windGust": 19.74,
                    "windBearing": 329,
                    "cloudCover": 0.59,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 389.7,
                },
                {
                    "time": 1617688800,
                    "summary": "Partly Cloudy",
                    "icon": "partly-cloudy-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 50.63,
                    "apparentTemperature": 50.63,
                    "dewPoint": 32.59,
                    "humidity": 0.5,
                    "pressure": 1014.6,
                    "windSpeed": 8.34,
                    "windGust": 20.06,
                    "windBearing": 327,
                    "cloudCover": 0.52,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 395.2,
                },
                {
                    "time": 1617692400,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 49.59,
                    "apparentTemperature": 46.23,
                    "dewPoint": 32.48,
                    "humidity": 0.52,
                    "pressure": 1014.5,
                    "windSpeed": 8.09,
                    "windGust": 19.59,
                    "windBearing": 319,
                    "cloudCover": 0.3,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 394.8,
                },
                {
                    "time": 1617696000,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 48.45,
                    "apparentTemperature": 44.78,
                    "dewPoint": 32.23,
                    "humidity": 0.53,
                    "pressure": 1014.6,
                    "windSpeed": 8.24,
                    "windGust": 19.14,
                    "windBearing": 310,
                    "cloudCover": 0.06,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 394.8,
                },
                {
                    "time": 1617699600,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 47.03,
                    "apparentTemperature": 43,
                    "dewPoint": 31.99,
                    "humidity": 0.56,
                    "pressure": 1014.7,
                    "windSpeed": 8.37,
                    "windGust": 19.29,
                    "windBearing": 307,
                    "cloudCover": 0.01,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 396.3,
                },
                {
                    "time": 1617703200,
                    "summary": "Clear",
                    "icon": "clear-night",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 45.59,
                    "apparentTemperature": 41.12,
                    "dewPoint": 31.98,
                    "humidity": 0.59,
                    "pressure": 1014.9,
                    "windSpeed": 8.62,
                    "windGust": 20.81,
                    "windBearing": 312,
                    "cloudCover": 0.02,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 397.7,
                },
                {
                    "time": 1617706800,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 44.43,
                    "apparentTemperature": 39.69,
                    "dewPoint": 32.06,
                    "humidity": 0.62,
                    "pressure": 1015.2,
                    "windSpeed": 8.63,
                    "windGust": 21.79,
                    "windBearing": 318,
                    "cloudCover": 0.04,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 397.3,
                },
                {
                    "time": 1617710400,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 44.75,
                    "apparentTemperature": 39.94,
                    "dewPoint": 32.7,
                    "humidity": 0.62,
                    "pressure": 1015.3,
                    "windSpeed": 9,
                    "windGust": 21.46,
                    "windBearing": 321,
                    "cloudCover": 0.05,
                    "uvIndex": 0,
                    "visibility": 10,
                    "ozone": 399.2,
                },
                {
                    "time": 1617714000,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 46.7,
                    "apparentTemperature": 42.24,
                    "dewPoint": 32.35,
                    "humidity": 0.57,
                    "pressure": 1015.2,
                    "windSpeed": 9.22,
                    "windGust": 19.98,
                    "windBearing": 326,
                    "cloudCover": 0.03,
                    "uvIndex": 1,
                    "visibility": 10,
                    "ozone": 401.3,
                },
                {
                    "time": 1617717600,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 49.26,
                    "apparentTemperature": 45.21,
                    "dewPoint": 30.87,
                    "humidity": 0.49,
                    "pressure": 1015.2,
                    "windSpeed": 9.71,
                    "windGust": 18.34,
                    "windBearing": 329,
                    "cloudCover": 0.01,
                    "uvIndex": 3,
                    "visibility": 10,
                    "ozone": 401.7,
                },
                {
                    "time": 1617721200,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0.0002,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 51.52,
                    "apparentTemperature": 51.52,
                    "dewPoint": 29.27,
                    "humidity": 0.42,
                    "pressure": 1014.9,
                    "windSpeed": 9.75,
                    "windGust": 16.42,
                    "windBearing": 330,
                    "cloudCover": 0,
                    "uvIndex": 4,
                    "visibility": 10,
                    "ozone": 402.1,
                },
                {
                    "time": 1617724800,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0.0002,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperature": 53.5,
                    "apparentTemperature": 53.5,
                    "dewPoint": 28.06,
                    "humidity": 0.37,
                    "pressure": 1014.3,
                    "windSpeed": 9.62,
                    "windGust": 15.02,
                    "windBearing": 328,
                    "cloudCover": 0,
                    "uvIndex": 5,
                    "visibility": 10,
                    "ozone": 398.6,
                },
                {
                    "time": 1617728400,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 55.58,
                    "apparentTemperature": 55.58,
                    "dewPoint": 27.5,
                    "humidity": 0.34,
                    "pressure": 1013.7,
                    "windSpeed": 9.17,
                    "windGust": 13.88,
                    "windBearing": 328,
                    "cloudCover": 0,
                    "uvIndex": 5,
                    "visibility": 10,
                    "ozone": 394.2,
                },
                {
                    "time": 1617732000,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 57.58,
                    "apparentTemperature": 57.58,
                    "dewPoint": 26.91,
                    "humidity": 0.31,
                    "pressure": 1013.2,
                    "windSpeed": 8.49,
                    "windGust": 12.65,
                    "windBearing": 327,
                    "cloudCover": 0.05,
                    "uvIndex": 5,
                    "visibility": 10,
                    "ozone": 384.9,
                },
                {
                    "time": 1617735600,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 59.69,
                    "apparentTemperature": 59.69,
                    "dewPoint": 26.45,
                    "humidity": 0.28,
                    "pressure": 1012.5,
                    "windSpeed": 8.41,
                    "windGust": 12.61,
                    "windBearing": 326,
                    "cloudCover": 0.04,
                    "uvIndex": 4,
                    "visibility": 10,
                    "ozone": 384,
                },
                {
                    "time": 1617739200,
                    "summary": "Clear",
                    "icon": "clear-day",
                    "precipIntensity": 0,
                    "precipProbability": 0,
                    "temperature": 61.28,
                    "apparentTemperature": 61.28,
                    "dewPoint": 25.54,
                    "humidity": 0.25,
                    "pressure": 1011.8,
                    "windSpeed": 8.58,
                    "windGust": 12.64,
                    "windBearing": 326,
                    "cloudCover": 0.02,
                    "uvIndex": 3,
                    "visibility": 10,
                    "ozone": 384.2,
                },
            ],
        },
        "daily": {
            "summary": "Light rain on Saturday.",
            "icon": "rain",
            "data": [
                {
                    "time": 1617508800,
                    "summary": "Partly cloudy throughout the day.",
                    "icon": "partly-cloudy-day",
                    "sunriseTime": 1617532500,
                    "sunsetTime": 1617578700,
                    "moonPhase": 0.77,
                    "precipIntensity": 0,
                    "precipIntensityMax": 0,
                    "precipIntensityMaxTime": 1617591600,
                    "precipProbability": 0,
                    "temperatureHigh": 60.22,
                    "temperatureHighTime": 1617570000,
                    "temperatureLow": 45.2,
                    "temperatureLowTime": 1617620400,
                    "apparentTemperatureHigh": 59.72,
                    "apparentTemperatureHighTime": 1617570000,
                    "apparentTemperatureLow": 40.54,
                    "apparentTemperatureLowTime": 1617620400,
                    "dewPoint": 30.41,
                    "humidity": 0.46,
                    "pressure": 1018.9,
                    "windSpeed": 4.41,
                    "windGust": 19.85,
                    "windGustTime": 1617593700,
                    "windBearing": 282,
                    "cloudCover": 0.49,
                    "uvIndex": 5,
                    "uvIndexTime": 1617559200,
                    "visibility": 10,
                    "ozone": 391.4,
                    "temperatureMin": 43.26,
                    "temperatureMinTime": 1617532860,
                    "temperatureMax": 60.22,
                    "temperatureMaxTime": 1617570000,
                    "apparentTemperatureMin": 42.21,
                    "apparentTemperatureMinTime": 1617533820,
                    "apparentTemperatureMax": 59.72,
                    "apparentTemperatureMaxTime": 1617570000,
                },
                {
                    "time": 1617595200,
                    "summary": "Clear throughout the day.",
                    "icon": "clear-day",
                    "sunriseTime": 1617618780,
                    "sunsetTime": 1617665160,
                    "moonPhase": 0.81,
                    "precipIntensity": 0.0001,
                    "precipIntensityMax": 0.0005,
                    "precipIntensityMaxTime": 1617609660,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperatureHigh": 60.4,
                    "temperatureHighTime": 1617654420,
                    "temperatureLow": 43.94,
                    "temperatureLowTime": 1617706800,
                    "apparentTemperatureHigh": 59.9,
                    "apparentTemperatureHighTime": 1617654420,
                    "apparentTemperatureLow": 39.69,
                    "apparentTemperatureLowTime": 1617706800,
                    "dewPoint": 32.56,
                    "humidity": 0.48,
                    "pressure": 1015.8,
                    "windSpeed": 11.94,
                    "windGust": 24.41,
                    "windGustTime": 1617656580,
                    "windBearing": 322,
                    "cloudCover": 0.13,
                    "uvIndex": 5,
                    "uvIndexTime": 1617642000,
                    "visibility": 10,
                    "ozone": 395,
                    "temperatureMin": 45.2,
                    "temperatureMinTime": 1617620700,
                    "temperatureMax": 60.4,
                    "temperatureMaxTime": 1617654420,
                    "apparentTemperatureMin": 40.51,
                    "apparentTemperatureMinTime": 1617621300,
                    "apparentTemperatureMax": 59.9,
                    "apparentTemperatureMaxTime": 1617654420,
                },
                {
                    "time": 1617681600,
                    "summary": "Clear throughout the day.",
                    "icon": "clear-day",
                    "sunriseTime": 1617705120,
                    "sunsetTime": 1617751620,
                    "moonPhase": 0.84,
                    "precipIntensity": 0.0001,
                    "precipIntensityMax": 0.0002,
                    "precipIntensityMaxTime": 1617726600,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperatureHigh": 62.72,
                    "temperatureHighTime": 1617743280,
                    "temperatureLow": 47.66,
                    "temperatureLowTime": 1617793020,
                    "apparentTemperatureHigh": 62.22,
                    "apparentTemperatureHighTime": 1617743280,
                    "apparentTemperatureLow": 45.48,
                    "apparentTemperatureLowTime": 1617793020,
                    "dewPoint": 30.94,
                    "humidity": 0.44,
                    "pressure": 1013.9,
                    "windSpeed": 7.91,
                    "windGust": 21.83,
                    "windGustTime": 1617707640,
                    "windBearing": 330,
                    "cloudCover": 0.14,
                    "uvIndex": 5,
                    "uvIndexTime": 1617728580,
                    "visibility": 10,
                    "ozone": 392.2,
                    "temperatureMin": 43.88,
                    "temperatureMinTime": 1617707880,
                    "temperatureMax": 62.72,
                    "temperatureMaxTime": 1617743280,
                    "apparentTemperatureMin": 39.57,
                    "apparentTemperatureMinTime": 1617708240,
                    "apparentTemperatureMax": 62.22,
                    "apparentTemperatureMaxTime": 1617743280,
                },
                {
                    "time": 1617768000,
                    "summary": "Clear throughout the day.",
                    "icon": "clear-day",
                    "sunriseTime": 1617791400,
                    "sunsetTime": 1617838080,
                    "moonPhase": 0.87,
                    "precipIntensity": 0.0006,
                    "precipIntensityMax": 0.0045,
                    "precipIntensityMaxTime": 1617786180,
                    "precipProbability": 0.02,
                    "precipType": "rain",
                    "temperatureHigh": 62.8,
                    "temperatureHighTime": 1617825960,
                    "temperatureLow": 51.41,
                    "temperatureLowTime": 1617879600,
                    "apparentTemperatureHigh": 62.3,
                    "apparentTemperatureHighTime": 1617825960,
                    "apparentTemperatureLow": 51.9,
                    "apparentTemperatureLowTime": 1617879600,
                    "dewPoint": 38.86,
                    "humidity": 0.56,
                    "pressure": 1015.1,
                    "windSpeed": 5.3,
                    "windGust": 13.15,
                    "windGustTime": 1617790200,
                    "windBearing": 96,
                    "cloudCover": 0.27,
                    "uvIndex": 5,
                    "uvIndexTime": 1617814680,
                    "visibility": 10,
                    "ozone": 393,
                    "temperatureMin": 47.66,
                    "temperatureMinTime": 1617793020,
                    "temperatureMax": 62.8,
                    "temperatureMaxTime": 1617825960,
                    "apparentTemperatureMin": 45.48,
                    "apparentTemperatureMinTime": 1617793020,
                    "apparentTemperatureMax": 62.3,
                    "apparentTemperatureMaxTime": 1617825960,
                },
                {
                    "time": 1617854400,
                    "summary": "Clear throughout the day.",
                    "icon": "clear-day",
                    "sunriseTime": 1617877680,
                    "sunsetTime": 1617924540,
                    "moonPhase": 0.9,
                    "precipIntensity": 0.0001,
                    "precipIntensityMax": 0.0003,
                    "precipIntensityMaxTime": 1617887100,
                    "precipProbability": 0.01,
                    "precipType": "rain",
                    "temperatureHigh": 59.62,
                    "temperatureHighTime": 1617899760,
                    "temperatureLow": 46.73,
                    "temperatureLowTime": 1617965760,
                    "apparentTemperatureHigh": 59.12,
                    "apparentTemperatureHighTime": 1617899760,
                    "apparentTemperatureLow": 44.22,
                    "apparentTemperatureLowTime": 1617964860,
                    "dewPoint": 42.57,
                    "humidity": 0.65,
                    "pressure": 1019.4,
                    "windSpeed": 6.73,
                    "windGust": 13.16,
                    "windGustTime": 1617929760,
                    "windBearing": 142,
                    "cloudCover": 0.22,
                    "uvIndex": 6,
                    "uvIndexTime": 1617900780,
                    "visibility": 10,
                    "ozone": 369.5,
                    "temperatureMin": 50.96,
                    "temperatureMinTime": 1617930060,
                    "temperatureMax": 59.62,
                    "temperatureMaxTime": 1617899760,
                    "apparentTemperatureMin": 51.45,
                    "apparentTemperatureMinTime": 1617930060,
                    "apparentTemperatureMax": 59.12,
                    "apparentTemperatureMaxTime": 1617899760,
                },
                {
                    "time": 1617940800,
                    "summary": "Light rain overnight.",
                    "icon": "cloudy",
                    "sunriseTime": 1617964020,
                    "sunsetTime": 1618011000,
                    "moonPhase": 0.94,
                    "precipIntensity": 0.001,
                    "precipIntensityMax": 0.008,
                    "precipIntensityMaxTime": 1618027200,
                    "precipProbability": 0.35,
                    "precipType": "rain",
                    "temperatureHigh": 56.11,
                    "temperatureHighTime": 1617990960,
                    "temperatureLow": 48.14,
                    "temperatureLowTime": 1618052400,
                    "apparentTemperatureHigh": 55.61,
                    "apparentTemperatureHighTime": 1617990960,
                    "apparentTemperatureLow": 44.74,
                    "apparentTemperatureLowTime": 1618052400,
                    "dewPoint": 42.8,
                    "humidity": 0.74,
                    "pressure": 1020.8,
                    "windSpeed": 7.61,
                    "windGust": 20.03,
                    "windGustTime": 1618027200,
                    "windBearing": 122,
                    "cloudCover": 0.96,
                    "uvIndex": 3,
                    "uvIndexTime": 1617987360,
                    "visibility": 10,
                    "ozone": 362.3,
                    "temperatureMin": 46.73,
                    "temperatureMinTime": 1617965760,
                    "temperatureMax": 56.11,
                    "temperatureMaxTime": 1617990960,
                    "apparentTemperatureMin": 44.22,
                    "apparentTemperatureMinTime": 1617964860,
                    "apparentTemperatureMax": 55.61,
                    "apparentTemperatureMaxTime": 1617990960,
                },
                {
                    "time": 1618027200,
                    "summary": "Light rain in the morning and afternoon.",
                    "icon": "rain",
                    "sunriseTime": 1618050300,
                    "sunsetTime": 1618097460,
                    "moonPhase": 0.97,
                    "precipIntensity": 0.0077,
                    "precipIntensityMax": 0.0151,
                    "precipIntensityMaxTime": 1618044720,
                    "precipProbability": 0.98,
                    "precipType": "rain",
                    "temperatureHigh": 49.83,
                    "temperatureHighTime": 1618082100,
                    "temperatureLow": 46.95,
                    "temperatureLowTime": 1618098000,
                    "apparentTemperatureHigh": 44.75,
                    "apparentTemperatureHighTime": 1618082520,
                    "apparentTemperatureLow": 43.13,
                    "apparentTemperatureLowTime": 1618095600,
                    "dewPoint": 43.9,
                    "humidity": 0.84,
                    "pressure": 1019,
                    "windSpeed": 9.51,
                    "windGust": 28.11,
                    "windGustTime": 1618078800,
                    "windBearing": 92,
                    "cloudCover": 1,
                    "uvIndex": 3,
                    "uvIndexTime": 1618074000,
                    "visibility": 10,
                    "ozone": 372.6,
                    "temperatureMin": 45.92,
                    "temperatureMinTime": 1618068960,
                    "temperatureMax": 51.58,
                    "temperatureMaxTime": 1618031160,
                    "apparentTemperatureMin": 41.23,
                    "apparentTemperatureMinTime": 1618069440,
                    "apparentTemperatureMax": 51.08,
                    "apparentTemperatureMaxTime": 1618031160,
                },
                {
                    "time": 1618113600,
                    "summary": "Overcast throughout the day.",
                    "icon": "cloudy",
                    "sunriseTime": 1618136640,
                    "sunsetTime": 1618183920,
                    "moonPhase": 1,
                    "precipIntensity": 0.0003,
                    "precipIntensityMax": 0.0013,
                    "precipIntensityMaxTime": 1618120380,
                    "precipProbability": 0.1,
                    "precipType": "rain",
                    "temperatureHigh": 52.68,
                    "temperatureHighTime": 1618172760,
                    "temperatureLow": 47.06,
                    "temperatureLowTime": 1618225200,
                    "apparentTemperatureHigh": 52.18,
                    "apparentTemperatureHighTime": 1618172760,
                    "apparentTemperatureLow": 46.18,
                    "apparentTemperatureLowTime": 1618225200,
                    "dewPoint": 40.28,
                    "humidity": 0.71,
                    "pressure": 1017.6,
                    "windSpeed": 6.88,
                    "windGust": 20.85,
                    "windGustTime": 1618113600,
                    "windBearing": 80,
                    "cloudCover": 0.97,
                    "uvIndex": 4,
                    "uvIndexTime": 1618159260,
                    "visibility": 10,
                    "ozone": 362.8,
                    "temperatureMin": 46.8,
                    "temperatureMinTime": 1618143300,
                    "temperatureMax": 52.68,
                    "temperatureMaxTime": 1618172760,
                    "apparentTemperatureMin": 43.24,
                    "apparentTemperatureMinTime": 1618143120,
                    "apparentTemperatureMax": 52.18,
                    "apparentTemperatureMaxTime": 1618172760,
                },
            ],
        },
        "alerts": [
            {
                "title": "Special Weather Statement",
                "regions": [
                    "Bronx",
                    "Kings (Brooklyn)",
                    "New York (Manhattan)",
                    "Northeast Suffolk",
                    "Northern Nassau",
                    "Northern Queens",
                    "Northern Westchester",
                    "Northwest Suffolk",
                    "Orange",
                    "Putnam",
                    "Richmond (Staten Is.)",
                    "Rockland",
                    "Southeast Suffolk",
                    "Southern Nassau",
                    "Southern Queens",
                    "Southern Westchester",
                    "Southwest Suffolk",
                ],
                "severity": "advisory",
                "time": 1617634800,
                "expires": 1617580800,
                "description": "There is an enhanced potential for brush fire spread.\n",
                "uri": "https://alerts.weather.gov/cap/wwacapget.php",
            }
        ],
        "flags": {
            "sources": [
                "nwspa",
                "cmc",
                "gfs",
                "hrrr",
                "icon",
                "isd",
                "madis",
                "nam",
                "sref",
                "darksky",
                "nearest-precip",
            ],
            "nearest-station": 0.816,
            "units": "us",
        },
        "offset": -4,
    },
    "latitude": 40.7128,
    "longitude": -74.006,
    "timezone": "America/New_York",
    "currently": "weird object",
}

json.dumps(sky_response)
