name: Checks
on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run pytests
        run: python -m pytest tests

  black:
    name: Black formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run black formatter
        run: black .
